# 2차원 데이터의 정리

## 두 데이터 사이의 관계를 나타내는 지표

In [5]:
import numpy as np
import pandas as pd

%precision 3
pd.set_option('precision', 3)


In [6]:
df = pd.read_csv('../data/ch2_scores_em.csv',
                 index_col='student number')

In [20]:
#english
en_scores = np.array(df[''])[:10]
en_scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [21]:
#mathematics
ma_scores = np.array(df[''])[:10]
ma_scores

array([65, 80, 63, 63, 76, 60, 81, 66, 78, 82], dtype=int64)

In [33]:
scores_df = pd.DataFrame()
scores_df

english  mathematics
student                      
A             42           65
B             69           80
C             56           63
D             41           63
E             57           76
F             48           60
G             65           81
H             49           66
I             65           78
J             58           82

### 공분산

In [44]:
summary_df = scores_df.copy()
summary_df['english_deviation'] =\
    summary_df[''] - summary_df[''].mean()
summary_df['mathematics_deviation'] =\
    summary_df[''] - summary_df[''].mean()
summary_df['product of deviations'] =\
    summary_df[''] * summary_df['']
summary_df

english  mathematics  english_deviation  mathematics_deviation  \
student                                                                   
A             42           65              -13.0                   -6.4   
B             69           80               14.0                    8.6   
C             56           63                1.0                   -8.4   
D             41           63              -14.0                   -8.4   
E             57           76                2.0                    4.6   
F             48           60               -7.0                  -11.4   
G             65           81               10.0                    9.6   
H             49           66               -6.0                   -5.4   
I             65           78               10.0                    6.6   
J             58           82                3.0                   10.6   

         product of deviations  
student                         
A                         83.2  
B                        120.4  
C                         -8.4  
D                        117.6  
E                          9.2  
F                         79.8  
G                         96.0  
H                         32.4  
I                         66.0  
J                         31.8

In [9]:
summary_df[''].mean()

62.800

In [10]:
%precision 3
cov_mat = np.cov(, , ddof=0)
cov_mat

array([[86.  , 62.8 ],
       [62.8 , 68.44]])

In [11]:
cov_mat[0, 1], cov_mat[1, 0]

(62.800000000000004, 62.800000000000004)

In [12]:
cov_mat[0, 0], cov_mat[1, 1]

(86.0, 68.44000000000001)

In [49]:
np.var(, ddof=0), np.var(, ddof=0)

(86.0, 68.44000000000001)

### 상관계수

In [14]:
np.cov(, , ddof=0)[0, 1] /\
    (np.std() * np.std())

0.8185692341186713

In [15]:
np.corrcoef(, )

array([[1.   , 0.819],
       [0.819, 1.   ]])

In [16]:
scores_df.corr()

english  mathematics
english        1.000        0.819
mathematics    0.819        1.000

In [51]:
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
english_scores = np.array(df[''])
math_scores = np.array(df[''])

fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111)
# 산점도
ax.scatter(, )
ax.set_xlabel('')
ax.set_ylabel('')

plt.show()